name: Create yarp changelog draft

on:
  push:
    branches: [main]
    paths:
      - "src/gateways/yarp/**"
      - "src/buildingblocks/**"
      - "src/Directory.Packages.props"
      - "src/Directory.Build.props"
      - "!src/gateways/yarp/Directory.Build.props"
      - "!src/gateways/yarp/CHANGELOG.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-draft:
    name: Generate release draft
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{steps.semantic.outputs.body}}
      tag-name: ${{steps.semantic.outputs.tag_name}}
      version: ${{steps.semantic.outputs.resolved_version}}
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 0
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v6
        id: semantic
        with:
          config-name: yarp-draft-release-drafter.yml
          disable-autolabeler: true
          disable-releaser: false
          commitish: main
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
  update-files:
    name: Update files
    runs-on: ubuntu-latest
    needs: [release-draft]
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        name: Checkout repository
      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.6
        with:
          file: "src/gateways/yarp/Directory.Build.props"
          version: ${{ needs.release-draft.outputs.version }}
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{needs.release-draft.outputs.tag-name}}
          release-notes: ${{needs.release-draft.outputs.changelog}}
          path-to-changelog: src/gateways/yarp/CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release/yarp
          delete-branch: true
          title: "chore: release ${{needs.release-draft.outputs.tag-name}}"
          commit-message: "chore: updated version"
          token: ${{ steps.generate-token.outputs.token }}
          labels: |
            skip-changelog
            release
